name: "Flutter tests & coverage"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_integration:
        description: 'Set to true to run integration tests'
        required: false
        default: 'true'

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Verify Flutter
        run: |
          flutter --version

      - name: Install dependencies
        run: |
          cd flutter_pomodoro_app
          flutter pub get

      - name: Prepare .env for tests
        run: |
          cd flutter_pomodoro_app
          if [ -f .env.sample ]; then
            cp .env.sample .env
          else
            printf "SCRIPTURE_API_KEY=dummy\n" > .env
            printf "BIBLE_ID=32664dc3288a28df-01\n" >> .env
            printf "ENABLE_LOCAL_NOTIFICATIONS=false\n" >> .env
          fi

      - name: Run unit/widget tests with coverage
        run: |
          cd flutter_pomodoro_app
          flutter test --coverage -r expanded
        env:
          CI: true

      - name: Convert coverage to CSV & MD (best-effort)
        run: |
          cd flutter_pomodoro_app
          dart run tool/lcov_to_csv.dart coverage/lcov.info coverage/coverage.csv || true
          dart run tool/csv_to_md.dart coverage/coverage.csv coverage/README.md || true

      - name: Upload to Codecov (if token set)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if [ -n "$CODECOV_TOKEN" ]; then
            bash <(curl -s https://codecov.io/bash) -f flutter_pomodoro_app/coverage/lcov.info -t "$CODECOV_TOKEN"
          else
            echo "No CODECOV_TOKEN set; skipping upload"
          fi

  integration-tests:
    if: ${{ github.event.inputs.run_integration == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          force-avd-creation: true
          emulator-options: '-no-window -no-audio -no-boot-anim'

      - name: Verify Flutter
        run: |
          flutter --version

      - name: Install dependencies
        run: |
          cd flutter_pomodoro_app
          flutter pub get

      - name: Prepare .env for tests
        run: |
          cd flutter_pomodoro_app
          if [ -f .env.sample ]; then
            cp .env.sample .env
          else
            printf "SCRIPTURE_API_KEY=dummy\n" > .env
            printf "ENABLE_LOCAL_NOTIFICATIONS=false\n" >> .env
          fi

      - name: Run integration tests
        run: |
          cd flutter_pomodoro_app
          flutter test integration_test -r expanded
        env:
          CI: true

      - name: Convert coverage to CSV & MD (best-effort)
        run: |
          cd flutter_pomodoro_app
          dart run tool/lcov_to_csv.dart coverage/lcov.info coverage/coverage.csv || true
          dart run tool/csv_to_md.dart coverage/coverage.csv coverage/README.md || true

      - name: Upload to Codecov (if token set)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if [ -n "$CODECOV_TOKEN" ]; then
            bash <(curl -s https://codecov.io/bash) -f flutter_pomodoro_app/coverage/lcov.info -t "$CODECOV_TOKEN"
          else
            echo "No CODECOV_TOKEN set; skipping upload"
          fi